// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7FOWuK7MeQIKCerxll79Zqh0DlU8rQ8w',
    appId: '1:432251828592:ios:fc71dfb42009ccddf537b5',
    messagingSenderId: '432251828592',
    projectId: 'kidlat2',
    storageBucket: 'kidlat2.appspot.com',
    iosClientId: '432251828592-qh4jteuvh7i304cl5dcnnndfe4kl11aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMao',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSyZ_42hzVo0TfAyp0n0RfICg1TXgBZ5o',
    appId: '1:432251828592:web:3e09faf81069d516f537b5',
    messagingSenderId: '432251828592',
    projectId: 'kidlat2',
    authDomain: 'kidlat2.firebaseapp.com',
    storageBucket: 'kidlat2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7FOWuK7MeQIKCerxll79Zqh0DlU8rQ8w',
    appId: '1:432251828592:ios:fc71dfb42009ccddf537b5',
    messagingSenderId: '432251828592',
    projectId: 'kidlat2',
    storageBucket: 'kidlat2.appspot.com',
    iosClientId: '432251828592-qh4jteuvh7i304cl5dcnnndfe4kl11aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMao',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhPEwfrSGsVNSyWwU24vXswH8WIjEX_n4',
    appId: '1:432251828592:android:c9c6c78647b1dfcdf537b5',
    messagingSenderId: '432251828592',
    projectId: 'kidlat2',
    storageBucket: 'kidlat2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSyZ_42hzVo0TfAyp0n0RfICg1TXgBZ5o',
    appId: '1:432251828592:web:1279646070490f2bf537b5',
    messagingSenderId: '432251828592',
    projectId: 'kidlat2',
    authDomain: 'kidlat2.firebaseapp.com',
    storageBucket: 'kidlat2.appspot.com',
  );

}